name: Connect to VM with PEM File

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger this workflow

jobs:
  connect_to_vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent and add private key from secrets
        run: |
          # Start the SSH agent
          eval "$(ssh-agent -s)"
          
          # Ensure the private key is decoded and added to the agent correctly
          echo "${{ secrets.PEMFILE }}" > /tmp/aws-key.pem
          chmod 600 /tmp/aws-key.pem
          ssh-add /tmp/aws-key.pem

      - name: Set up SSH config
        run: |
          mkdir -p ~/.ssh
          echo -e "Host vm\n  HostName ${ { secrets.VMHOST } }\n  User ${ { secrets.VMUSER } }\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Connect to VM and run a command
        run: |
          # SSH into the VM using the SSH agent (no need to specify key)
          ssh ${ { secrets.VMUSER } }@${ { secrets.VMHOST } } "echo 'Successfully connected to the VM!'"
